' ########################################################################################
' Microsoft Windows
' File: DHtmldid.inc
' Contents: DISPIDs for DHTMLEd.OCX
' Copyright (c) 2011 José Roca
' Portions Copyright (c) Microsoft Corporation.
' All Rights Reserved.
' THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER
' EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
' MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
' ########################################################################################

#INCLUDE THIS ONCE
%DHTMLDID_INC = 1

'// methods and properties
%DISPID_LOADDOCUMENT             = 1
%DISPID_EXECCOMMAND              = 2
%DISPID_QUERYSTATUS              = 3
%DISPID_SAVEDOCUMENT             = 4
%DISPID_SETCONTEXTMENU           = 5
%DISPID_DOCUMENT                 = 6
%DISPID_ACTIVATEAPPLETS          = 7
%DISPID_ACTIVATEACTIVEXCONTROLS  = 8
%DISPID_ACTIVATEDTCS             = 9
%DISPID_SHOWDETAILS              = 11
%DISPID_SHOWBORDERS              = 12
%DISPID_DHTMLEDITAPPEARANCE      = 13
%DISPID_DHTMLEDITSCROLLBARS      = 14
%DISPID_SCROLLBARAPPEARANCE      = 15
%DISPID_SOURCECODEPRESERVATION   = 16
%DISPID_DOCUMENTHTML             = 17
%DISPID_ABSOLUTEDROPMODE         = 18
%DISPID_SNAPTOGRIDX              = 19
%DISPID_SNAPTOGRIDY              = 20
%DISPID_SNAPTOGRID               = 21
%DISPID_ISDIRTY                  = 22
%DISPID_CURRENTDOCUMENTPATH      = 23
%DISPID_BASEURL                  = 24
%DISPID_DOCUMENTTITLE            = 25
%DISPID_BROWSEMODE               = 26
%DISPID_NEWDOCUMENT              = 27
%DISPID_PRINT                    = 28
%DISPID_LOADURL                  = 29
%DISPID_USEDIVONCR               = 30
%DISPID_FILTERSRCCODE            = 31
%DISPID_REFRESHDOC               = 32
%DISPID_BUSY                     = 33

'// events
%DISPID_DOCUMENTCOMPLETE         = 1
%DISPID_DISPLAYCHANGED           = 2
%DISPID_SHOWCONTEXTMENU          = 3
%DISPID_CONTEXTMENUACTION        = 4
%DISPID_ONMOUSEDOWN              = 5
%DISPID_ONMOUSEMOVE              = 6
%DISPID_ONMOUSEUP                = 7
%DISPID_ONMOUSEOUT               = 8
%DISPID_ONMOUSEOVER              = 9
%DISPID_ONCLICK                  = 10
%DISPID_ONDBLCLICK               = 11
%DISPID_ONKEYDOWN                = 12
%DISPID_ONKEYPRESS               = 13
%DISPID_ONKEYUP                  = 14
%DISPID_ONBLUR                   = 15
%DISPID_ONREADYSTATECHANGE       = 16


%DISPID_TABLEPARAMS_NUMROWS      = 1
%DISPID_TABLEPARAMS_NUMCOLS      = 2
%DISPID_TABLEPARAMS_TABLEATTRS   = 3
%DISPID_TABLEPARAMS_CELLATTRS    = 4
%DISPID_TABLEPARAMS_CAPTION      = 5

%DISPID_NAMESPARAM_NAMES         = 1
