' ########################################################################################
' Microsoft Windows
' File: MSAcmDlg.inc
' Contents: Audio Compression Manager Common Dialogs Identifiers
' Copyright (c) 2011 José Roca
' Portions Copyright (c) Microsoft Corporation.
' All Rights Reserved.
' THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER
' EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
' MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
' ########################################################################################

#INCLUDE THIS ONCE
%MSACMDLG_INC = 1

%DLG_ACMFORMATCHOOSE_ID              = 70
%IDD_ACMFORMATCHOOSE_BTN_HELP        = 9
%IDD_ACMFORMATCHOOSE_CMB_CUSTOM      = 100
%IDD_ACMFORMATCHOOSE_CMB_FORMATTAG   = 101
%IDD_ACMFORMATCHOOSE_CMB_FORMAT      = 102
%IDD_ACMFORMATCHOOSE_BTN_SETNAME     = 103
%IDD_ACMFORMATCHOOSE_BTN_DELNAME     = 104


%DLG_ACMFILTERCHOOSE_ID              = 71
%IDD_ACMFILTERCHOOSE_BTN_HELP        = 9
%IDD_ACMFILTERCHOOSE_CMB_CUSTOM      = 100
%IDD_ACMFILTERCHOOSE_CMB_FILTERTAG   = 101
%IDD_ACMFILTERCHOOSE_CMB_FILTER      = 102
%IDD_ACMFILTERCHOOSE_BTN_SETNAME     = 103
%IDD_ACMFILTERCHOOSE_BTN_DELNAME     = 104
