' ########################################################################################
' Microsoft Windows
' File: triediid.inc
' Contents: GUIDs for TriEdit.dll Active Document
' Copyright (c) 2011 José Roca
' Portions Copyright (c) Microsoft Corporation.
' All Rights Reserved.
' THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER
' EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
' MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
' ########################################################################################

#INCLUDE THIS ONCE
%TRIEDIID_INC = 1

$GUID_TriEditCommandGroup = GUID$("{2582F1C0-084E-11D1-9A0E-006097C9B344}")
$IID_ITriEditDocument     = GUID$("{438DA5DF-F171-11D0-984E-0000F80270F8}")
$LIBID_TRIEDITLib         = GUID$("{438DA5D1-F171-11D0-984E-0000F80270F8}")
$CLSID_TriEditDocument    = GUID$("{438DA5E0-F171-11D0-984E-0000F80270F8}")
